// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/deploy/IAO": {
            "post": {
                "description": "Deploy a new contract with the given parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deployment"
                ],
                "summary": "Deploy contract",
                "parameters": [
                    {
                        "description": "Deployment parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.DeployIAORequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.StandardResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.StandardResponse"
                        }
                    }
                }
            }
        },
        "/deploy/staking": {
            "post": {
                "description": "Deploy a new contract with the given parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deployment"
                ],
                "summary": "Deploy contract",
                "parameters": [
                    {
                        "description": "Deployment parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.DeployStakingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.StandardResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.StandardResponse"
                        }
                    }
                }
            }
        },
        "/deploy/token": {
            "post": {
                "description": "Deploy a new contract with the given parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deployment"
                ],
                "summary": "Deploy contract",
                "parameters": [
                    {
                        "description": "Deployment parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.DeployTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.StandardResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.StandardResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.DeployIAORequest": {
            "type": "object",
            "required": [
                "duration_hours",
                "owner",
                "reward_amount",
                "reward_token",
                "start_timestamp"
            ],
            "properties": {
                "duration_hours": {
                    "type": "integer",
                    "example": 72
                },
                "owner": {
                    "type": "string",
                    "example": "0xAE5015960Ff1E3ad095a7037533b1e3E7240b54D"
                },
                "reward_amount": {
                    "type": "string",
                    "example": "2000000000000000000000000000"
                },
                "reward_token": {
                    "type": "string",
                    "example": "0x07D325030dA1A8c1f96C414BFFbe4fBD539CED45"
                },
                "start_timestamp": {
                    "type": "integer",
                    "example": 1743663600
                }
            }
        },
        "api.DeployStakingRequest": {
            "type": "object",
            "required": [
                "nft",
                "owner",
                "project_name",
                "reward_amount_per_year",
                "reward_token"
            ],
            "properties": {
                "nft": {
                    "type": "string",
                    "example": "0x07D325030dA1A8c1f96C414BFFbe4fBD539CED45"
                },
                "owner": {
                    "type": "string",
                    "example": "0xAE5015960Ff1E3ad095a7037533b1e3E7240b54D"
                },
                "project_name": {
                    "type": "string",
                    "example": "My Project"
                },
                "reward_amount_per_year": {
                    "type": "string",
                    "example": "2000000000000000000000000000"
                },
                "reward_token": {
                    "type": "string",
                    "example": "0x07D325030dA1A8c1f96C414BFFbe4fBD539CED45"
                }
            }
        },
        "api.DeployTokenRequest": {
            "type": "object",
            "required": [
                "owner",
                "token_amount_can_mint_per_year",
                "token_init_supply",
                "token_name",
                "token_supply_fixed_years",
                "token_symbol"
            ],
            "properties": {
                "owner": {
                    "type": "string",
                    "example": "0xAE5015960Ff1E3ad095a7037533b1e3E7240b54D"
                },
                "token_amount_can_mint_per_year": {
                    "type": "string",
                    "example": "6000000000000000000000000000"
                },
                "token_init_supply": {
                    "type": "string",
                    "example": "2000000000000000000000000000"
                },
                "token_name": {
                    "type": "string",
                    "example": "TokenName"
                },
                "token_supply_fixed_years": {
                    "type": "integer",
                    "example": 8
                },
                "token_symbol": {
                    "type": "string",
                    "example": "TN"
                }
            }
        },
        "api.StandardResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Status code",
                    "type": "integer"
                },
                "data": {
                    "description": "Data"
                },
                "message": {
                    "description": "Message",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
