definitions:
  api.DeployIAORequest:
    properties:
      duration_hours:
        example: 72
        type: integer
      owner:
        example: 0xAE5015960Ff1E3ad095a7037533b1e3E7240b54D
        type: string
      reward_amount:
        example: "2000000000000000000000000000"
        type: string
      reward_token:
        example: 0x07D325030dA1A8c1f96C414BFFbe4fBD539CED45
        type: string
      start_timestamp:
        example: 1743663600
        type: integer
    required:
    - duration_hours
    - owner
    - reward_amount
    - reward_token
    - start_timestamp
    type: object
  api.DeployPaymentRequest:
    properties:
      address_free_request_count:
        description: Number of free requests available for each address
        example: 10
        type: integer
      free_request_count:
        description: Number of free requests available for the contract
        example: 100
        type: integer
      min_usd_balance_for_using_free_request:
        description: Minimum USD balance required for using free requests for the
          address
        example: 100000
        type: integer
      owner:
        description: Owner address of the contract
        example: 0xAE5015960Ff1E3ad095a7037533b1e3E7240b54D
        type: string
      payment_token:
        description: Payment token address
        example: 0x07D325030dA1A8c1f96C414BFFbe4fBD539CED45
        type: string
      vip_monthly_quotas:
        description: Number of VIP requests available for each month
        example: 10
        type: integer
      vip_price_fixed_count:
        description: Fixed price for VIP requests
        example: 100000
        type: integer
      vip_price_monthly:
        description: Monthly price for VIP requests
        example: 100000
        type: integer
    required:
    - address_free_request_count
    - free_request_count
    - min_usd_balance_for_using_free_request
    - owner
    - payment_token
    - vip_monthly_quotas
    - vip_price_fixed_count
    - vip_price_monthly
    type: object
  api.DeployStakingRequest:
    properties:
      nft:
        example: 0x07D325030dA1A8c1f96C414BFFbe4fBD539CED45
        type: string
      owner:
        example: 0xAE5015960Ff1E3ad095a7037533b1e3E7240b54D
        type: string
      project_name:
        example: Project
        type: string
      reward_amount_per_year:
        example: "2000000000000000000000000000"
        type: string
      reward_token:
        example: 0x07D325030dA1A8c1f96C414BFFbe4fBD539CED45
        type: string
    required:
    - nft
    - owner
    - project_name
    - reward_amount_per_year
    - reward_token
    type: object
  api.DeployTokenRequest:
    properties:
      owner:
        example: 0xAE5015960Ff1E3ad095a7037533b1e3E7240b54D
        type: string
      token_amount_can_mint_per_year:
        example: "6000000000000000000000000000"
        type: string
      token_init_supply:
        example: "2000000000000000000000000000"
        type: string
      token_name:
        example: TokenName
        type: string
      token_supply_fixed_years:
        example: 8
        type: integer
      token_symbol:
        example: TN
        type: string
    required:
    - owner
    - token_amount_can_mint_per_year
    - token_init_supply
    - token_name
    - token_supply_fixed_years
    - token_symbol
    type: object
  api.StandardResponse:
    properties:
      code:
        description: Status code
        type: integer
      data:
        description: Data
      message:
        description: Message
        type: string
    type: object
info:
  contact: {}
paths:
  /deploy/IAO:
    post:
      consumes:
      - application/json
      description: Deploy a new contract with the given parameters
      parameters:
      - description: Deployment parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.DeployIAORequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.StandardResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.StandardResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.StandardResponse'
      summary: Deploy contract
      tags:
      - deployment
  /deploy/payment:
    post:
      consumes:
      - application/json
      description: Deploy a new contract with the given parameters
      parameters:
      - description: Deployment parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.DeployPaymentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.StandardResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.StandardResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.StandardResponse'
      summary: Deploy contract
      tags:
      - deployment
  /deploy/staking:
    post:
      consumes:
      - application/json
      description: Deploy a new contract with the given parameters
      parameters:
      - description: Deployment parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.DeployStakingRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.StandardResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.StandardResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.StandardResponse'
      summary: Deploy contract
      tags:
      - deployment
  /deploy/token:
    post:
      consumes:
      - application/json
      description: Deploy a new contract with the given parameters
      parameters:
      - description: Deployment parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.DeployTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.StandardResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.StandardResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.StandardResponse'
      summary: Deploy contract
      tags:
      - deployment
swagger: "2.0"
